function createfigure(xgroupdata1, ydata1)
%CREATEFIGURE(xgroupdata1, ydata1)
%  XGROUPDATA1:  boxchart xgroupdata
%  YDATA1:  boxchart ydata

%  Auto-generated by MATLAB on 10-Apr-2022 23:16:42

% Create figure
figure1 = figure('InvertHardcopy','off','NumberTitle','off','Name','Figure',...
    'Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create boxchart
boxchart(xgroupdata1,ydata1);

% Create ylabel
ylabel({'Brain NAA Concentration (mM)'},'FontSize',11);

% Create xlabel
xlabel({''},'FontSize',11);

% Create title
title({'Figure 2'},'FontSize',11);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[-0.5 1.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[11.8 13.4]);
% Uncomment the following line to preserve the Z-limits of the axes
zlim(axes1,[-1 1]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XTickLabel',{'','Amyloid Negative','','Amyloid Positive',''});
% hold on;

% g = mean(posmean);
% plot(pet,g);
% hold on;
% h = mean(negmean);
% plot(pet, h);
